# Stage 1: Build Vite project
FROM node:latest AS build
ARG ENVIRONMENT=prod
WORKDIR /app
COPY . .
RUN npm install
# Run the appropriate build script based on the environment
RUN if [ "${ENVIRONMENT}" = "test" ]; then \
    npm run buildtest; \
    else \
    npm run build; \
    fi

# Stage 2: Serve static files with Nginx
FROM nginx:alpine
COPY default.conf /etc/nginx/conf.d/
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80