export const countryPhoneCode = [
  { code: "AF", prefix: "+93", emoji: "🇦🇫", name: "Afghanistan" },
  { code: "AX", prefix: "+358-18", emoji: "🇦🇽", name: "Aland Islands" },
  { code: "AL", prefix: "+355", emoji: "🇦🇱", name: "Albania" },
  { code: "DZ", prefix: "+213", emoji: "🇩🇿", name: "Algeria" },
  { code: "AS", prefix: "+1-684", emoji: "🇦🇸", name: "American Samoa" },
  { code: "AD", prefix: "+376", emoji: "🇦🇩", name: "Andorra" },
  { code: "AO", prefix: "+244", emoji: "🇦🇴", name: "Angola" },
  { code: "AI", prefix: "+1-264", emoji: "🇦🇮", name: "Anguilla" },
  { code: "AG", prefix: "+1-268", emoji: "🇦🇬", name: "Antigua and Barbuda" },
  { code: "AR", prefix: "+54", emoji: "🇦🇷", name: "Argentina" },
  { code: "AM", prefix: "+374", emoji: "🇦🇲", name: "Armenia" },
  { code: "AW", prefix: "+297", emoji: "🇦🇼", name: "Aruba" },
  { code: "AU", prefix: "+61", emoji: "🇦🇺", name: "Australia" },
  { code: "AT", prefix: "+43", emoji: "🇦🇹", name: "Austria" },
  { code: "AZ", prefix: "+994", emoji: "🇦🇿", name: "Azerbaijan" },
  { code: "BS", prefix: "+1-242", emoji: "🇧🇸", name: "Bahamas" },
  { code: "BH", prefix: "+973", emoji: "🇧🇭", name: "Bahrain" },
  { code: "BD", prefix: "+880", emoji: "🇧🇩", name: "Bangladesh" },
  { code: "BB", prefix: "+1-246", emoji: "🇧🇧", name: "Barbados" },
  { code: "BY", prefix: "+375", emoji: "🇧🇾", name: "Belarus" },
  { code: "BE", prefix: "+32", emoji: "🇧🇪", name: "Belgium" },
  { code: "BZ", prefix: "+501", emoji: "🇧🇿", name: "Belize" },
  { code: "BJ", prefix: "+229", emoji: "🇧🇯", name: "Benin" },
  { code: "BM", prefix: "+1-441", emoji: "🇧🇲", name: "Bermuda" },
  { code: "BT", prefix: "+975", emoji: "🇧🇹", name: "Bhutan" },
  { code: "BO", prefix: "+591", emoji: "🇧🇴", name: "Bolivia" },
  {
    code: "BQ",
    prefix: "+599",
    emoji: "🇧🇶",
    name: "Bonaire, Saint Eustatius and Saba ",
  },
  { code: "BA", prefix: "+387", emoji: "🇧🇦", name: "Bosnia and Herzegovina" },
  { code: "BW", prefix: "+267", emoji: "🇧🇼", name: "Botswana" },
  { code: "BR", prefix: "+55", emoji: "🇧🇷", name: "Brazil" },
  {
    code: "IO",
    prefix: "+246",
    emoji: "🇮🇴",
    name: "British Indian Ocean Territory",
  },
  { code: "VG", prefix: "+1-284", emoji: "🇻🇬", name: "British Virgin Islands" },
  { code: "BN", prefix: "+673", emoji: "🇧🇳", name: "Brunei" },
  { code: "BG", prefix: "+359", emoji: "🇧🇬", name: "Bulgaria" },
  { code: "BF", prefix: "+226", emoji: "🇧🇫", name: "Burkina Faso" },
  { code: "BI", prefix: "+257", emoji: "🇧🇮", name: "Burundi" },
  { code: "KH", prefix: "+855", emoji: "🇰🇭", name: "Cambodia" },
  { code: "CM", prefix: "+237", emoji: "🇨🇲", name: "Cameroon" },
  { code: "CA", prefix: "+1", emoji: "🇨🇦", name: "Canada" },
  { code: "CV", prefix: "+238", emoji: "🇨🇻", name: "Cape Verde" },
  { code: "KY", prefix: "+1-345", emoji: "🇰🇾", name: "Cayman Islands" },
  { code: "CF", prefix: "+236", emoji: "🇨🇫", name: "Central African Republic" },
  { code: "TD", prefix: "+235", emoji: "🇹🇩", name: "Chad" },
  { code: "CL", prefix: "+56", emoji: "🇨🇱", name: "Chile" },
  { code: "CN", prefix: "+86", emoji: "🇨🇳", name: "China" },
  { code: "CX", prefix: "+61", emoji: "🇨🇽", name: "Christmas Island" },
  { code: "CC", prefix: "+61", emoji: "🇨🇨", name: "Cocos Islands" },
  { code: "CO", prefix: "+57", emoji: "🇨🇴", name: "Colombia" },
  { code: "KM", prefix: "+269", emoji: "🇰🇲", name: "Comoros" },
  { code: "CK", prefix: "+682", emoji: "🇨🇰", name: "Cook Islands" },
  { code: "CR", prefix: "+506", emoji: "🇨🇷", name: "Costa Rica" },
  { code: "HR", prefix: "+385", emoji: "🇭🇷", name: "Croatia" },
  { code: "CU", prefix: "+53", emoji: "🇨🇺", name: "Cuba" },
  { code: "CW", prefix: "+599", emoji: "🇨🇼", name: "Curacao" },
  { code: "CY", prefix: "+357", emoji: "🇨🇾", name: "Cyprus" },
  { code: "CZ", prefix: "+420", emoji: "🇨🇿", name: "Czech Republic" },
  {
    code: "CD",
    prefix: "+243",
    emoji: "🇨🇩",
    name: "Democratic Republic of the Congo",
  },
  { code: "DK", prefix: "+45", emoji: "🇩🇰", name: "Denmark" },
  { code: "DJ", prefix: "+253", emoji: "🇩🇯", name: "Djibouti" },
  { code: "DM", prefix: "+1-767", emoji: "🇩🇲", name: "Dominica" },
  {
    code: "DO",
    prefix: "+1-829",
    emoji: "🇩🇴",
    name: "Dominican Republic",
  },
  {
    code: "DO",
    prefix: "+1-809",
    emoji: "🇩🇴",
    name: "Dominican Republic",
  },
  { code: "TL", prefix: "+670", emoji: "🇹🇱", name: "East Timor" },
  { code: "EC", prefix: "+593", emoji: "🇪🇨", name: "Ecuador" },
  { code: "EG", prefix: "+20", emoji: "🇪🇬", name: "Egypt" },
  { code: "SV", prefix: "+503", emoji: "🇸🇻", name: "El Salvador" },
  { code: "GQ", prefix: "+240", emoji: "🇬🇶", name: "Equatorial Guinea" },
  { code: "ER", prefix: "+291", emoji: "🇪🇷", name: "Eritrea" },
  { code: "EE", prefix: "+372", emoji: "🇪🇪", name: "Estonia" },
  { code: "ET", prefix: "+251", emoji: "🇪🇹", name: "Ethiopia" },
  { code: "FK", prefix: "+500", emoji: "🇫🇰", name: "Falkland Islands" },
  { code: "FO", prefix: "+298", emoji: "🇫🇴", name: "Faroe Islands" },
  { code: "FJ", prefix: "+679", emoji: "🇫🇯", name: "Fiji" },
  { code: "FI", prefix: "+358", emoji: "🇫🇮", name: "Finland" },
  { code: "FR", prefix: "+33", emoji: "🇫🇷", name: "France" },
  { code: "GF", prefix: "+594", emoji: "🇬🇫", name: "French Guiana" },
  { code: "PF", prefix: "+689", emoji: "🇵🇫", name: "French Polynesia" },
  { code: "GA", prefix: "+241", emoji: "🇬🇦", name: "Gabon" },
  { code: "GM", prefix: "+220", emoji: "🇬🇲", name: "Gambia" },
  { code: "GE", prefix: "+995", emoji: "🇬🇪", name: "Georgia" },
  { code: "DE", prefix: "+49", emoji: "🇩🇪", name: "Germany" },
  { code: "GH", prefix: "+233", emoji: "🇬🇭", name: "Ghana" },
  { code: "GI", prefix: "+350", emoji: "🇬🇮", name: "Gibraltar" },
  { code: "GR", prefix: "+30", emoji: "🇬🇷", name: "Greece" },
  { code: "GL", prefix: "+299", emoji: "🇬🇱", name: "Greenland" },
  { code: "GD", prefix: "+1-473", emoji: "🇬🇩", name: "Grenada" },
  { code: "GP", prefix: "+590", emoji: "🇬🇵", name: "Guadeloupe" },
  { code: "GU", prefix: "+1-671", emoji: "🇬🇺", name: "Guam" },
  { code: "GT", prefix: "+502", emoji: "🇬🇹", name: "Guatemala" },
  { code: "GG", prefix: "+44-1481", emoji: "🇬🇬", name: "Guernsey" },
  { code: "GN", prefix: "+224", emoji: "🇬🇳", name: "Guinea" },
  { code: "GW", prefix: "+245", emoji: "🇬🇼", name: "Guinea-Bissau" },
  { code: "GY", prefix: "+592", emoji: "🇬🇾", name: "Guyana" },
  { code: "HT", prefix: "+509", emoji: "🇭🇹", name: "Haiti" },
  { code: "HN", prefix: "+504", emoji: "🇭🇳", name: "Honduras" },
  { code: "HK", prefix: "+852", emoji: "🇭🇰", name: "Hong Kong" },
  { code: "HU", prefix: "+36", emoji: "🇭🇺", name: "Hungary" },
  { code: "IS", prefix: "+354", emoji: "🇮🇸", name: "Iceland" },
  { code: "IN", prefix: "+91", emoji: "🇮🇳", name: "India" },
  { code: "ID", prefix: "+62", emoji: "🇮🇩", name: "Indonesia" },
  { code: "IR", prefix: "+98", emoji: "🇮🇷", name: "Iran" },
  { code: "IQ", prefix: "+964", emoji: "🇮🇶", name: "Iraq" },
  { code: "IE", prefix: "+353", emoji: "🇮🇪", name: "Ireland" },
  { code: "IM", prefix: "+44-1624", emoji: "🇮🇲", name: "Isle of Man" },
  { code: "IL", prefix: "+972", emoji: "🇮🇱", name: "Israel" },
  { code: "IT", prefix: "+39", emoji: "🇮🇹", name: "Italy" },
  { code: "CI", prefix: "+225", emoji: "🇨🇮", name: "Ivory Coast" },
  { code: "JM", prefix: "+1-876", emoji: "🇯🇲", name: "Jamaica" },
  { code: "JP", prefix: "+81", emoji: "🇯🇵", name: "Japan" },
  { code: "JE", prefix: "+44-1534", emoji: "🇯🇪", name: "Jersey" },
  { code: "JO", prefix: "+962", emoji: "🇯🇴", name: "Jordan" },
  { code: "KZ", prefix: "+7", emoji: "🇰🇿", name: "Kazakhstan" },
  { code: "KE", prefix: "+254", emoji: "🇰🇪", name: "Kenya" },
  { code: "KI", prefix: "+686", emoji: "🇰🇮", name: "Kiribati" },
  { code: "XK", prefix: "+383", emoji: "🇽🇰", name: "Kosovo" },
  { code: "KW", prefix: "+965", emoji: "🇰🇼", name: "Kuwait" },
  { code: "KG", prefix: "+996", emoji: "🇰🇬", name: "Kyrgyzstan" },
  { code: "LA", prefix: "+856", emoji: "🇱🇦", name: "Laos" },
  { code: "LV", prefix: "+371", emoji: "🇱🇻", name: "Latvia" },
  { code: "LB", prefix: "+961", emoji: "🇱🇧", name: "Lebanon" },
  { code: "LS", prefix: "+266", emoji: "🇱🇸", name: "Lesotho" },
  { code: "LR", prefix: "+231", emoji: "🇱🇷", name: "Liberia" },
  { code: "LY", prefix: "+218", emoji: "🇱🇾", name: "Libya" },
  { code: "LI", prefix: "+423", emoji: "🇱🇮", name: "Liechtenstein" },
  { code: "LT", prefix: "+370", emoji: "🇱🇹", name: "Lithuania" },
  { code: "LU", prefix: "+352", emoji: "🇱🇺", name: "Luxembourg" },
  { code: "MO", prefix: "+853", emoji: "🇲🇴", name: "Macao" },
  { code: "MK", prefix: "+389", emoji: "🇲🇰", name: "Macedonia" },
  { code: "MG", prefix: "+261", emoji: "🇲🇬", name: "Madagascar" },
  { code: "MW", prefix: "+265", emoji: "🇲🇼", name: "Malawi" },
  { code: "MY", prefix: "+60", emoji: "🇲🇾", name: "Malaysia" },
  { code: "MV", prefix: "+960", emoji: "🇲🇻", name: "Maldives" },
  { code: "ML", prefix: "+223", emoji: "🇲🇱", name: "Mali" },
  { code: "MT", prefix: "+356", emoji: "🇲🇹", name: "Malta" },
  { code: "MH", prefix: "+692", emoji: "🇲🇭", name: "Marshall Islands" },
  { code: "MQ", prefix: "+596", emoji: "🇲🇶", name: "Martinique" },
  { code: "MR", prefix: "+222", emoji: "🇲🇷", name: "Mauritania" },
  { code: "MU", prefix: "+230", emoji: "🇲🇺", name: "Mauritius" },
  { code: "YT", prefix: "+262", emoji: "🇾🇹", name: "Mayotte" },
  { code: "MX", prefix: "+52", emoji: "🇲🇽", name: "Mexico" },
  { code: "FM", prefix: "+691", emoji: "🇫🇲", name: "Micronesia" },
  { code: "MD", prefix: "+373", emoji: "🇲🇩", name: "Moldova" },
  { code: "MC", prefix: "+377", emoji: "🇲🇨", name: "Monaco" },
  { code: "MN", prefix: "+976", emoji: "🇲🇳", name: "Mongolia" },
  { code: "ME", prefix: "+382", emoji: "🇲🇪", name: "Montenegro" },
  { code: "MS", prefix: "+1-664", emoji: "🇲🇸", name: "Montserrat" },
  { code: "MA", prefix: "+212", emoji: "🇲🇦", name: "Morocco" },
  { code: "MZ", prefix: "+258", emoji: "🇲🇿", name: "Mozambique" },
  { code: "MM", prefix: "+95", emoji: "🇲🇲", name: "Myanmar" },
  { code: "NA", prefix: "+264", emoji: "🇳🇦", name: "Namibia" },
  { code: "NR", prefix: "+674", emoji: "🇳🇷", name: "Nauru" },
  { code: "NP", prefix: "+977", emoji: "🇳🇵", name: "Nepal" },
  { code: "NL", prefix: "+31", emoji: "🇳🇱", name: "Netherlands" },
  { code: "NC", prefix: "+687", emoji: "🇳🇨", name: "New Caledonia" },
  { code: "NZ", prefix: "+64", emoji: "🇳🇿", name: "New Zealand" },
  { code: "NI", prefix: "+505", emoji: "🇳🇮", name: "Nicaragua" },
  { code: "NE", prefix: "+227", emoji: "🇳🇪", name: "Niger" },
  { code: "NG", prefix: "+234", emoji: "🇳🇬", name: "Nigeria" },
  { code: "NU", prefix: "+683", emoji: "🇳🇺", name: "Niue" },
  { code: "NF", prefix: "+672", emoji: "🇳🇫", name: "Norfolk Island" },
  { code: "KP", prefix: "+850", emoji: "🇰🇵", name: "North Korea" },
  {
    code: "MP",
    prefix: "+1-670",
    emoji: "🇲🇵",
    name: "Northern Mariana Islands",
  },
  { code: "NO", prefix: "+47", emoji: "🇳🇴", name: "Norway" },
  { code: "OM", prefix: "+968", emoji: "🇴🇲", name: "Oman" },
  { code: "PK", prefix: "+92", emoji: "🇵🇰", name: "Pakistan" },
  { code: "PW", prefix: "+680", emoji: "🇵🇼", name: "Palau" },
  { code: "PS", prefix: "+970", emoji: "🇵🇸", name: "Palestinian Territory" },
  { code: "PA", prefix: "+507", emoji: "🇵🇦", name: "Panama" },
  { code: "PG", prefix: "+675", emoji: "🇵🇬", name: "Papua New Guinea" },
  { code: "PY", prefix: "+595", emoji: "🇵🇾", name: "Paraguay" },
  { code: "PE", prefix: "+51", emoji: "🇵🇪", name: "Peru" },
  { code: "PH", prefix: "+63", emoji: "🇵🇭", name: "Philippines" },
  { code: "PN", prefix: "+870", emoji: "🇵🇳", name: "Pitcairn" },
  { code: "PL", prefix: "+48", emoji: "🇵🇱", name: "Poland" },
  { code: "PT", prefix: "+351", emoji: "🇵🇹", name: "Portugal" },
  { code: "PR", prefix: "+1-787", emoji: "🇵🇷", name: "Puerto Rico" },
  { code: "PR", prefix: "+1-939", emoji: "🇵🇷", name: "Puerto Rico" },
  { code: "QA", prefix: "+974", emoji: "🇶🇦", name: "Qatar" },
  { code: "CG", prefix: "+242", emoji: "🇨🇬", name: "Republic of the Congo" },
  { code: "RE", prefix: "+262", emoji: "🇷🇪", name: "Reunion" },
  { code: "RO", prefix: "+40", emoji: "🇷🇴", name: "Romania" },
  { code: "RU", prefix: "+7", emoji: "🇷🇺", name: "Russia" },
  { code: "RW", prefix: "+250", emoji: "🇷🇼", name: "Rwanda" },
  { code: "BL", prefix: "+590", emoji: "🇧🇱", name: "Saint Barthelemy" },
  { code: "SH", prefix: "+290", emoji: "🇸🇭", name: "Saint Helena" },
  { code: "KN", prefix: "+1-869", emoji: "🇰🇳", name: "Saint Kitts and Nevis" },
  { code: "LC", prefix: "+1-758", emoji: "🇱🇨", name: "Saint Lucia" },
  { code: "MF", prefix: "+590", emoji: "🇲🇫", name: "Saint Martin" },
  {
    code: "PM",
    prefix: "+508",
    emoji: "🇵🇲",
    name: "Saint Pierre and Miquelon",
  },
  {
    code: "VC",
    prefix: "+1-784",
    emoji: "🇻🇨",
    name: "Saint Vincent and the Grenadines",
  },
  { code: "WS", prefix: "+685", emoji: "🇼🇸", name: "Samoa" },
  { code: "SM", prefix: "+378", emoji: "🇸🇲", name: "San Marino" },
  { code: "ST", prefix: "+239", emoji: "🇸🇹", name: "Sao Tome and Principe" },
  { code: "SA", prefix: "+966", emoji: "🇸🇦", name: "Saudi Arabia" },
  { code: "SN", prefix: "+221", emoji: "🇸🇳", name: "Senegal" },
  { code: "RS", prefix: "+381", emoji: "🇷🇸", name: "Serbia" },
  { code: "SC", prefix: "+248", emoji: "🇸🇨", name: "Seychelles" },
  { code: "SL", prefix: "+232", emoji: "🇸🇱", name: "Sierra Leone" },
  { code: "SG", prefix: "+65", emoji: "🇸🇬", name: "Singapore" },
  { code: "SX", prefix: "+599", emoji: "🇸🇽", name: "Sint Maarten" },
  { code: "SK", prefix: "+421", emoji: "🇸🇰", name: "Slovakia" },
  { code: "SI", prefix: "+386", emoji: "🇸🇮", name: "Slovenia" },
  { code: "SB", prefix: "+677", emoji: "🇸🇧", name: "Solomon Islands" },
  { code: "SO", prefix: "+252", emoji: "🇸🇴", name: "Somalia" },
  { code: "ZA", prefix: "+27", emoji: "🇿🇦", name: "South Africa" },
  { code: "KR", prefix: "+82", emoji: "🇰🇷", name: "South Korea" },
  { code: "SS", prefix: "+211", emoji: "🇸🇸", name: "South Sudan" },
  { code: "ES", prefix: "+34", emoji: "🇪🇸", name: "Spain" },
  { code: "LK", prefix: "+94", emoji: "🇱🇰", name: "Sri Lanka" },
  { code: "SD", prefix: "+249", emoji: "🇸🇩", name: "Sudan" },
  { code: "SR", prefix: "+597", emoji: "🇸🇷", name: "Suriname" },
  { code: "SJ", prefix: "+47", emoji: "🇸🇯", name: "Svalbard and Jan Mayen" },
  { code: "SZ", prefix: "+268", emoji: "🇸🇿", name: "Swaziland" },
  { code: "SE", prefix: "+46", emoji: "🇸🇪", name: "Sweden" },
  { code: "CH", prefix: "+41", emoji: "🇨🇭", name: "Switzerland" },
  { code: "SY", prefix: "+963", emoji: "🇸🇾", name: "Syria" },
  { code: "TW", prefix: "+886", emoji: "🇹🇼", name: "Taiwan" },
  { code: "TJ", prefix: "+992", emoji: "🇹🇯", name: "Tajikistan" },
  { code: "TZ", prefix: "+255", emoji: "🇹🇿", name: "Tanzania" },
  { code: "TH", prefix: "+66", emoji: "🇹🇭", name: "Thailand" },
  { code: "TG", prefix: "+228", emoji: "🇹🇬", name: "Togo" },
  { code: "TK", prefix: "+690", emoji: "🇹🇰", name: "Tokelau" },
  { code: "TO", prefix: "+676", emoji: "🇹🇴", name: "Tonga" },
  { code: "TT", prefix: "+1-868", emoji: "🇹🇹", name: "Trinidad and Tobago" },
  { code: "TN", prefix: "+216", emoji: "🇹🇳", name: "Tunisia" },
  { code: "TR", prefix: "+90", emoji: "🇹🇷", name: "Turkey" },
  { code: "TM", prefix: "+993", emoji: "🇹🇲", name: "Turkmenistan" },
  {
    code: "TC",
    prefix: "+1-649",
    emoji: "🇹🇨",
    name: "Turks and Caicos Islands",
  },
  { code: "TV", prefix: "+688", emoji: "🇹🇻", name: "Tuvalu" },
  { code: "VI", prefix: "+1-340", emoji: "🇻🇮", name: "U.S. Virgin Islands" },
  { code: "UG", prefix: "+256", emoji: "🇺🇬", name: "Uganda" },
  { code: "UA", prefix: "+380", emoji: "🇺🇦", name: "Ukraine" },
  { code: "AE", prefix: "+971", emoji: "🇦🇪", name: "United Arab Emirates" },
  { code: "GB", prefix: "+44", emoji: "🇬🇧", name: "United Kingdom" },
  { code: "US", prefix: "+1", emoji: "🇺🇸", name: "United States" },
  { code: "UY", prefix: "+598", emoji: "🇺🇾", name: "Uruguay" },
  { code: "UZ", prefix: "+998", emoji: "🇺🇿", name: "Uzbekistan" },
  { code: "VU", prefix: "+678", emoji: "🇻🇺", name: "Vanuatu" },
  { code: "VA", prefix: "+379", emoji: "🇻🇦", name: "Vatican" },
  { code: "VE", prefix: "+58", emoji: "🇻🇪", name: "Venezuela" },
  { code: "VN", prefix: "+84", emoji: "🇻🇳", name: "Vietnam" },
  { code: "WF", prefix: "+681", emoji: "🇼🇫", name: "Wallis and Futuna" },
  { code: "EH", prefix: "+212", emoji: "🇪🇭", name: "Western Sahara" },
  { code: "YE", prefix: "+967", emoji: "🇾🇪", name: "Yemen" },
  { code: "ZM", prefix: "+260", emoji: "🇿🇲", name: "Zambia" },
  { code: "ZW", prefix: "+263", emoji: "🇿🇼", name: "Zimbabwe" },
];
