name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Build the Docker image
        run: docker build -t elberthomax/ecommerce-react -f Dockerfile.prod .
      
      - name: Login into dockerhub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Push image to dockerhub
        run: docker push elberthomax/ecommerce-react
      
      # Download and Install IBM Cloud CLI
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Get K8s context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.AZURE_CLUSTER_NAME }}
          cluster-name: ${{ env.AZURE_CLUSTER_NAME }}
          admin: 'false'
          use-kubelogin: 'true'
      - run: kubectl rollout restart deployment ecommerce-react-depl

    
